// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVerifyCustomDomainParams creates a new VerifyCustomDomainParams object
// with the default values initialized.
func NewVerifyCustomDomainParams() *VerifyCustomDomainParams {
	var ()
	return &VerifyCustomDomainParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyCustomDomainParamsWithTimeout creates a new VerifyCustomDomainParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyCustomDomainParamsWithTimeout(timeout time.Duration) *VerifyCustomDomainParams {
	var ()
	return &VerifyCustomDomainParams{

		timeout: timeout,
	}
}

// NewVerifyCustomDomainParamsWithContext creates a new VerifyCustomDomainParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyCustomDomainParamsWithContext(ctx context.Context) *VerifyCustomDomainParams {
	var ()
	return &VerifyCustomDomainParams{

		Context: ctx,
	}
}

// NewVerifyCustomDomainParamsWithHTTPClient creates a new VerifyCustomDomainParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyCustomDomainParamsWithHTTPClient(client *http.Client) *VerifyCustomDomainParams {
	var ()
	return &VerifyCustomDomainParams{
		HTTPClient: client,
	}
}

/*
VerifyCustomDomainParams contains all the parameters to send to the API endpoint
for the verify custom domain operation typically these are written to a http.Request
*/
type VerifyCustomDomainParams struct {

	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify custom domain params
func (o *VerifyCustomDomainParams) WithTimeout(timeout time.Duration) *VerifyCustomDomainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify custom domain params
func (o *VerifyCustomDomainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify custom domain params
func (o *VerifyCustomDomainParams) WithContext(ctx context.Context) *VerifyCustomDomainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify custom domain params
func (o *VerifyCustomDomainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify custom domain params
func (o *VerifyCustomDomainParams) WithHTTPClient(client *http.Client) *VerifyCustomDomainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify custom domain params
func (o *VerifyCustomDomainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteID adds the siteID to the verify custom domain params
func (o *VerifyCustomDomainParams) WithSiteID(siteID string) *VerifyCustomDomainParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the verify custom domain params
func (o *VerifyCustomDomainParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyCustomDomainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
