// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// VerifyCustomDomainReader is a Reader for the VerifyCustomDomain structure.
type VerifyCustomDomainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyCustomDomainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyCustomDomainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyCustomDomainDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyCustomDomainOK creates a VerifyCustomDomainOK with default headers values
func NewVerifyCustomDomainOK() *VerifyCustomDomainOK {
	return &VerifyCustomDomainOK{}
}

/*
VerifyCustomDomainOK handles this case with default header values.

OK
*/
type VerifyCustomDomainOK struct {
	Payload *models.Result
}

func (o *VerifyCustomDomainOK) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/ssl/verify_custom_domain][%d] verifyCustomDomainOK  %+v", 200, o.Payload)
}

func (o *VerifyCustomDomainOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *VerifyCustomDomainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVerifyCustomDomainDefault creates a VerifyCustomDomainDefault with default headers values
func NewVerifyCustomDomainDefault(code int) *VerifyCustomDomainDefault {
	return &VerifyCustomDomainDefault{
		_statusCode: code,
	}
}

/*
VerifyCustomDomainDefault handles this case with default header values.

error
*/
type VerifyCustomDomainDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the verify custom domain default response
func (o *VerifyCustomDomainDefault) Code() int {
	return o._statusCode
}

func (o *VerifyCustomDomainDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/ssl/verify_custom_domain][%d] verifyCustomDomain default  %+v", o._statusCode, o.Payload)
}

func (o *VerifyCustomDomainDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *VerifyCustomDomainDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
